groups:
  - name: example_alerts
    rules:
      - alert: NodeDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Node {{ $labels.instance }} is down
          description: Node {{ $labels.instance }} has been down for 1 min